id = "godot-theme"
name = "Godot Theme"
version = "1.1.0"
schema_version = 1
authors = ["Enzo Suares <mail@enzosuares.fr>"]
description = "A theme inspired by the Godot editor and GDScript highlighting"
repository = "https://github.com/D4r3NPo/zed-theme-godot"
